### ISSUE TITLE
Try sleeping more

### ISSUE THREAD

**Issue by waldoj** [waldoj/sickness#31]
I get 7–8 hours of sleep each night, with an average of 7½ hours. That's well within recommended norms, but maybe that's just not enough.

Try sleeping more every night for a defined period.

* [x] figure out how many hours to experiment with
* [x] figure out how long I should do it for
* [x] do it

**Comment by waldoj** [comment]
Observation: this all started a little over a week after my eldest kid started kindergarten, and the whole house changed from waking at 7:30 to waking at 6:30. Looking at my calendar, the onset would have been while I was putting on a three-day workshop for a client, which would have meant at least 1–2 nights of terrible hotel-sleep, and inevitably staying up late prepping for the next day, and waking early to get on-site with the client.

And the closest thing that I've had to a vacation was spending a week in India, but that was pretty intensely scheduled, and was 9½ hours ahead (UTC+05:30), so the jet lag was wicked. I think I was in bed 8–9 hours of sleep most nights, but the sleep was not great.

**Comment by waldoj** [comment]
[This list of symptoms seems pretty solid](https://www.nhlbi.nih.gov/health-topics/sleep-deprivation-and-deficiency).

**Comment by waldoj** [comment]
The NIH-recommended amount of sleep is 7–8 hours, but it's totally reasonable that I might just need _more._ I can't find any solid data, but I'm going to speculate that I'll need at least one week to experiment. And I also want to overshoot on the amount of sleep, so I'm going to say 9 hours is what I need.

**Comment by waldoj** [comment]
http://www.sleepeducation.org/sleep-disorders-by-category/hypersomnias/insufficient-sleep-syndrome
> Insufficient sleep syndrome is easily treated once it is found to be the problem. You will simply need to begin sleeping for a longer period of time each night. This should end the symptoms.
🙏

**Comment by jessamynwest** [comment]
One pretty easy way to test this out is PILLS. I'm a chronic poor sleeper and I definitely notice performance deficits for lack of a better word when I'm sleep-deprived. I have a little arsenal of stuff which will put me to sleep when it's not otherwise going to happen. I use them sparingly but it's like pressing a big ol reset button on the slow drain-circling that is chronic bad sleeping. If that otherwise solves your issues, you can stop taking them and then work on assidiuous sleep hygeine stuff (which mostly works for me, ymmv). Good luck!

**Comment by jessamynwest** [comment]
Also I assume you have a sleep tracker you like, but I get a lot of value out of the totally low-tech app from the VA. Good for looking for trends. Has NO cute language. Just works.

https://mobile.va.gov/app/cbt-i-coach

**Comment by waldoj** [comment]
As far as I know, the quality of my sleep is great. I _may_ need a sleep study (#16), but generally I fall asleep quickly and sleep through the night. The only real challenge for me is actually hauling my carcass up the stairs and into bed on time. :)

I've just been using iOS's Health, and iOS Notes, but I'll try out CBT-i Coach — thanks!

**Comment by waldoj** [comment]
A update to this issue. I started doing this on Saturday (thought forgot to move the card on the kanban board until just now). I've slept an average of 8.4 hours per night for the past week, and 8.6 since I started to make an effort to sleep more (as a part of this weekly sprint), and wow I have I seen results. I felt somewhat better, mentally, yesterday. Today I felt _significantly_ mentally better. I can't really keep up with my own thoughts. It's like sprinting when I've only been able to crawl. There's no way my mind is at 100%, but it's a whole lot better. Physically, I feel somewhat better, maybe? I'm still tired, I still feel generally unwell.

To be clear, I don't know whether I feel better because of #28, #9, #5, or because of sleep. But it sure feels to me like it's sleep that's doing it. I'm going to continue all four activities as planned, and I expect that, for the next spring, I'll gradually curtail the other activities and see if I remain improved.

**Comment by waldoj** [comment]
An update: Wednesday improvements evaporated on Thursday morning, when I woke up sick. Today I was sicker still. (A nasty cold, I expect.) Expectations of improvement are on hold until I recover.

**Comment by waldoj** [comment]
My cold has largely passed. My mind works again. I'm even more convinced that this is because of sleep, but I can't know that for certain.

I'm 14 nights into this. I've averaged 8:22 minutes of sleep (not time in bed, but _sleep_), which is less than I would have guessed. (With a median and a mode of 8:30.) I feel mentally at about 80%, I'm guessing, but physically still at, like, 50%. I think I just need more recovery time, but I also think I need more sleep. 8:30 would be a healthier average. Historically, anecdotally, I have done best when I average 8:30 of sleep.

**Comment by waldoj** [comment]
I'm cured.
