### ISSUE TITLE
Get a full metabolic panel

### ISSUE THREAD

**Issue by waldoj** [waldoj/sickness#6]
Glucose, BUN, sodium, CO2, calcium, etc.

**Comment by waldoj** [comment]
Had it in late February. Everything fine.

**Comment by markjaquith** [comment]
Iron?

**Comment by waldoj** [comment]
I didn't think I'd had iron tested until you suggested it — turns out I did, and it's listed in #13.

**Comment by waldoj** [comment]
For the record, these were covered in the metabolic panel:

* glucose
* BUN
* creatinine
* eGFR
* sodium
* potassium
* chloride
* CO2
* calcium
* protein
* albumin
* globulin
* bilirubin
* alkaline phosphate
* AST
